name: Test AWS Connection

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::529370324189:role/GitHubActionsRole
          aws-region: us-east-1
      
      - name: Test AWS connection
        run: |
          echo "Testing AWS connection..."
          aws sts get-caller-identity
          echo "✅ AWS connection successful!"
      
      - name: Check for existing CDK bootstrap
        run: |
          echo "Checking CDK bootstrap status..."
          if aws cloudformation describe-stacks --stack-name CDKToolkit 2>/dev/null; then
            echo "✅ CDK is already bootstrapped"
          else
            echo "❌ CDK needs to be bootstrapped"
            echo "Run: cd infrastructure && npx cdk bootstrap"
          fi